[features]
seeds = false
skip-lint = false
[programs.localnet]
albedo = "8QyTSgBy2Msab5yXRLnPhvrto59MAxjtw2PPWbnui4Nx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/praky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
