[features]
seeds = false
skip-lint = false
[programs.localnet]
data_monetisation = "9pG7mPqQ4mX6VMgG4uZSiNRkryCutyoHh4Hit2rpp6cj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/praky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
