[features]
seeds = false
skip-lint = false
[programs.localnet]
insurance_disbursal_escrow = "PaYj25PZhw6ckeff1KbTBXweHqFh8dyBsdphZAG7rFF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/praky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
