[features]
seeds = false
skip-lint = false

[programs.localnet]
insurance_pool_vault = "CrSyuUEDMHudgQXNCTnA1y7GgPrUdqFYRQ7knP13kjWp"

[programs.devnet]
insurance_pool_vault = "CrSyuUEDMHudgQXNCTnA1y7GgPrUdqFYRQ7knP13kjWp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/praky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
